Xarm testing
dxyang/rewardlearning-robot pull request #2
Opened 2023-04-10 22:10 UTC by Jacob6819

Merge XARM code into main branch

2023-04-11 01:57 UTC, Jacob6819 commented
We probably want to delete the zoe vr file from the main branch once we finish this pull request

2023-04-11 14:38 UTC, dxyang requested changes
mostly nits but looks good overall!

2023-04-11 14:38 UTC, dxyang commented on .idea/.gitignore
I would add `.idea` to the `.gitignore` file at the root of the repo instead of checking these IDE specific files in

2023-04-11 14:38 UTC, dxyang commented on robot/base_robot.py
> +from xarm.wrapper import XArmAPI
these shouldn't need to be imported in the base robot file

2023-04-11 14:38 UTC, dxyang commented on robot/base_robot.py
> +from PIL import Image
or any of these changes

2023-04-11 14:38 UTC, dxyang commented on robot/data.py
> +
are you all dealing with variable length demos? most of the code assumes all demos are of the same length (i.e., if the robot gets to the goal state it just does nothing for a few timesteps)

2023-04-11 14:38 UTC, dxyang commented on robot/utils.py
>      "default": [600, 600, 600, 600, 250, 150, 50],
do these changes make sense if you're not using the franka?

2023-04-11 14:38 UTC, dxyang commented on robot/vr.py
> +        """
i'm guessing this is copy/paste code, but this doesn't sound like a right handed coordinate system.... :(

2023-04-11 14:38 UTC, dxyang commented on robot/xarm_env.py
> +        message.data = np.asarray(xyz*10).copy()
should this 10 be calling the scale factor? seems like a magic random number

2023-04-11 14:38 UTC, dxyang commented on robot/xarm_env.py
> +        return np.array(position[:3]) / 10
likewise what's this 10 for? if it's unit conversion add some comment or documentation

2023-04-11 14:38 UTC, dxyang commented on robot/xarm_env.py
> +        # 6-DoF (x, y, z, roll, pitch, yaw) (absolute or deltas)
comment is now invalid since you're just doing pos control

2023-04-11 14:38 UTC, dxyang commented on zoey_vr_test.py
> +"""
maybe make a `scratch` or `experimental` folder at the repo root and move this into there?

2023-04-11 14:38 UTC, dxyang commented on robot/robot_listener.py
> +pos = np.array([553.490479, 29.007273, 424.868439])
maybe a comment here explaining why these numbers are super

2023-04-11 14:38 UTC, dxyang commented on robot/record_xarm_vr.py
> +    - https://github.com/AGI-Labs/franka_control/blob/master/playback.py
update documentation accordingly

2023-04-11 14:38 UTC, dxyang commented on robot/record_xarm_vr.py
> +                deltas = oculus.get_deltas() / 8
what's going on here lol

2023-04-14 20:04 UTC, dxyang approved these changes

2023-04-14 20:19 UTC, merged